### PR TITLE
Move 2014 talks to a separate folder, start 2015 folder

### PR DESCRIPTION
**Pull request by tkelman**
Anyone trying to collect slides yet?

Alternative would be to rename this repo to presentations2014 and start a new repo for this year's talks, either way works for me.

### CODE REVIEW

**Comment by ninjin** [comment]
The only problem that I see is that moving the files will break any links to the repository.  Perhaps we should create a new repository "JuliaCon2015Slides"?

**Comment by alanedelman** [comment]
I would actually like to see every juliacon archived and accessible: 
web page, program, slides, videos, photos

**Comment by tkelman** [comment]
I agree, and would be good to do so before people forget where they put their presentation material.

I hadn't thought about the broken links issue, that is unfortunate. So the alternative of renaming this repo to put 2014 somewhere in the name would be preferred I think (GitHub will auto-redirect after a repository rename). That can't be proposed as a PR, so if someone can go and do that, and create a new repository for 2015 we can close this.

**Comment by stevengj** [comment]
We could put manual redirect links for the 2014 slides.

**Comment by tkelman** [comment]
@stevengj I don't know whether that would work. Worth testing maybe if committing symlinks to the repo would result in redirects? Or rename this repo, and create a new one with a more future-proof directory structure that has this repo as a 2014 submodule?

**Comment by stevengj** [comment]
The plan moving forward is to put everything on DSpace.

**Comment by tkelman** [comment]
I'd have preferred github, but good enough.

**Comment by stevengj** [comment]
DSpace has the advantage of giving a permanent (or at least life-of-MIT long-term) archive with citable DOIs.

**Pull request closed without merging**
